### ISSUE TITLE
Hi，are there some issues in the dataloader class of cifar?

### ISSUE THREAD

**Issue by LanXiaoPang613** [HotanLee/SFA#2]
Hi，are there some issues in the dataloader class of cifar? the details are shown in the following img:
![image](https://github.com/HotanLee/SFA/assets/35187545/2fc8fb67-26c9-4f6d-9d72-a68a08e11892)
In the red retangle, the "cls_num_list" is used while the "cls_id_list" is used in yellow oval?

**Comment by HotanLee** [comment]
Thanks for your attention. 
The definition of many/medium/few shot in CIFAR-10 and CIFAR-100 is different. In CIFAR-10, it's defined according to class index (i.e., _**cls_id_list**_, as the simulated CIFAR-10 follows long-tailed distribution and class 0 is the head class), whereas in CIFAR-100, it's defined according to the number of images in each class (i.e., _**cls_num_list**_). This is a common setting and you can find it in many previous literature in long-tailed learning like Arxiv:2004.03706.
